<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>FirmlyPaid.EndToEnd.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Testcontainers.MsSql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FirmlyPaid.Shared\FirmlyPaid.Shared.csproj" />
    <ProjectReference Include="..\..\src\FirmlyPaid.Gateway\FirmlyPaid.Gateway.csproj" />
    <ProjectReference Include="..\..\src\FirmlyPaid.Enrolment.Api\FirmlyPaid.Enrolment.Api.csproj" />
    <ProjectReference Include="..\..\src\FirmlyPaid.Matching.Api\FirmlyPaid.Matching.Api.csproj" />
    <ProjectReference Include="..\..\src\FirmlyPaid.AccountLink.Api\FirmlyPaid.AccountLink.Api.csproj" />
    <ProjectReference Include="..\..\src\FirmlyPaid.Payments.Api\FirmlyPaid.Payments.Api.csproj" />
    <ProjectReference Include="..\..\src\FirmlyPaid.Risk.Api\FirmlyPaid.Risk.Api.csproj" />
    <ProjectReference Include="..\..\src\FirmlyPaid.TillIntegration.Api\FirmlyPaid.TillIntegration.Api.csproj" />
  </ItemGroup>

</Project>
