// <auto-generated />
using System;
using FirmlyPaid.Data.Vault;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirmlyPaid.Data.Vault.Migrations
{
    [DbContext(typeof(FirmlyPaidVaultDbContext))]
    partial class FirmlyPaidVaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FirmlyPaid.Data.Vault.Entities.Bucket", b =>
                {
                    b.Property<Guid>("TemplateOwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdDigits7to10Bucket")
                        .HasColumnType("int");

                    b.HasKey("TemplateOwnerId");

                    b.HasIndex("IdDigits7to10Bucket");

                    b.ToTable("Buckets");
                });

            modelBuilder.Entity("FirmlyPaid.Data.Vault.Entities.VeinTemplate", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("EncryptedTemplate")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("FingerPosition")
                        .HasColumnType("int");

                    b.Property<string>("KeyVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("QualityScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TemplateOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TransformSeedId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TemplateId");

                    b.HasIndex("TemplateOwnerId", "RevokedAt");

                    b.ToTable("VeinTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
